//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Mimari_Kesin_Proje_Kontrol_Listesi
{
    using System;
    using System.ComponentModel.DataAnnotations.Schema;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class PDFSaverEntities : DbContext
    {
        public PDFSaverEntities()
            : base("name=PDFSaverEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<DataPdf> data_pdf { get; set; }
    }

    [Table("data_pdf")]
    public class DataPdf
    {
        public int Id { get; set; }
        public string Dosya_Adi { get; set; }
        public string Dosya_Yolu { get; set; }
    }
}
